import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, Platform, ScrollView, TouchableOpacity, ActivityIndicator, Alert, Animated } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Linking from 'expo-linking';
import { useTheme, useAuth } from '../../lib/context';
import { buildStudentContext } from '../../lib/adaptiveEngine';
import { callSarvam } from '../../lib/ai';
import { Fonts } from '../../constants/fonts';
import { Radii } from '../../constants/colors';
import { PrimaryButton, AnimatedScreenWrapper } from '../../components/ui/premium';

export default function ParentalReportScreen() {
  const { colors } = useTheme();
  const { studentId } = useAuth();
  const [report, setReport] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      if (!studentId) return;
      try {
        const contextStr = await buildStudentContext(studentId);
        
        const prompt = `You are an AI academic advisor. Generate a professional, empathetic "Parental Summary Report" based on the following student data.
Format it nicely but do NOT use Markdown (no asterisks or hash symbols) because this will be put into an email body in plain text.
Include:
1. A brief overview of their recent study habits and time spent.
2. Areas where they are excelling (Strong Subjects).
3. Areas requiring more attention (Weak Subjects).
4. Their emotional well-being based on recent mood logs.
5. One actionable tip for the parent to support them.

Student Data:
${contextStr}`;

        const response = await callSarvam([
          { role: 'system', content: 'You are a professional educational counselor generating plain-text reports for parents.' },
          { role: 'user', content: prompt }
        ], 'report_generation');
        
        // Clean up any stray markdown
        const plainText = response.replace(/\*\*/g, '').replace(/\*/g, '').replace(/#/g, '');
        setReport(plainText);
      } catch (err) {
        console.error(err);
        setReport("Error generating report. Please check your AI API key and connection.");
      } finally {
        setLoading(false);
      }
    })();
  }, [studentId]);

  const sendEmail = async () => {
    if (!report) return;
    const subject = encodeURIComponent("StudyMate AI - Weekly Academic & Well-being Report");
    const body = encodeURIComponent(report + "\n\n---\nGenerated by StudyMate AI");
    const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;
    
    try {
      const canOpen = await Linking.canOpenURL(mailtoUrl);
      if (canOpen || Platform.OS === 'web') {
        await Linking.openURL(mailtoUrl);
      } else {
        Alert.alert("Error", "No email app configured on this device.");
      }
    } catch (e) {
      Alert.alert("Error", "Could not open email app.");
    }
  };

  return (
    <AnimatedScreenWrapper style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.header}>
        <TouchableOpacity 
          onPress={() => {
  try {
    router.back();
  } catch {
    router.replace('/');
  }
}}
          style={[styles.backBtn, { borderColor: colors.borderSubtle, backgroundColor: colors.surface1 }]}
        >
          <Ionicons name="arrow-back" size={20} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.textPrimary, fontFamily: Fonts.display }]}>Parental Report Card</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={[styles.iconWrap, { backgroundColor: colors.surface1, borderColor: colors.borderSubtle }]}>
          <Ionicons name="mail-unread-outline" size={36} color={colors.accent} />
        </View>
        <Text style={[styles.title, { color: colors.textPrimary, fontFamily: Fonts.display }]}>Weekly AI Summary</Text>
        <Text style={[styles.subtitle, { color: colors.textSecondary, fontFamily: Fonts.body }]}>
          A comprehensive overview of academic performance and emotional well-being to share with parents.
        </Text>

        <View style={[styles.reportCard, { backgroundColor: colors.surface1, borderColor: colors.borderSubtle }]}>
          {loading ? (
            <View style={{ padding: 40, alignItems: 'center' }}>
              <ActivityIndicator size="large" color={colors.accent} />
              <Text style={{ marginTop: 16, color: colors.textTertiary, fontFamily: Fonts.body, textAlign: 'center' }}>
                Analyzing student behavioral graph...
              </Text>
            </View>
          ) : (
            <Text style={[styles.reportText, { color: colors.textPrimary, fontFamily: Fonts.body }]}>{report}</Text>
          )}
        </View>

        {!loading && (
          <PrimaryButton
            label="Send via Gmail / Email"
            icon={<Ionicons name="send" size={16} color={colors.textInverse} />}
            onPress={sendEmail}
          />
        )}
      </ScrollView>
    </AnimatedScreenWrapper>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: Platform.OS === 'ios' ? 60 : 40 },
  header: { 
    paddingHorizontal: 20, 
    paddingVertical: 12, 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center' 
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 18, letterSpacing: -0.4 },
  content: { padding: 20, paddingBottom: 40 },
  iconWrap: { 
    width: 72, 
    height: 72, 
    borderRadius: 36, 
    alignItems: 'center', 
    justifyContent: 'center', 
    marginBottom: 20, 
    alignSelf: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  title: { fontSize: 22, marginBottom: 8, textAlign: 'center', letterSpacing: -0.4 },
  subtitle: { fontSize: 14, lineHeight: 20, marginBottom: 24, textAlign: 'center' },
  reportCard: { 
    padding: 20, 
    borderRadius: Radii.card, 
    borderWidth: StyleSheet.hairlineWidth, 
    marginBottom: 8 
  },
  reportText: { fontSize: 14, lineHeight: 22 },
});
